Feature/check schedules endpoints
Rise-Vision/messaging-service pull request #91
Opened 2021-02-05 18:08 UTC by santiagonoguez

## Description
- Consider connection from schedule and endpoint id.
- Use schedule id instead of display id for data structures in case a display id was not provided but an schedule id was.
- Update manual tests to accound for schedule id scenario.
- No ban checks still implemented

## Motivation and Context
Messaging service now needs to support also connections related to an endpoint id / schedule id, with validation according to the design docs:

https://docs.google.com/document/d/1eKG9gKLxNT6_l22mvvVE6qgMaR4vQw079YtSePCYW8M/edit#
https://docs.google.com/document/d/1G4UcGtoHxLEpvoTXUi7bZ9Jo1-wLAF5d5kkU6uhKb4Q/edit#heading=h.2e5j3jrgtz0d ( schedule / display validation section )

If a scheduleId parameter is received, it will be validated and authorized as an endpointId/scheduleId connection; otherwise it will validated as a displayId/machineId connection ( as before ). This way, the current behavior is not affected by current PR changes.

## How Has This Been Tested?
Automated integration tests concernting new scheduleId/endpointId parameters were added.

Also, manual test script was modified to support an optional SCHEDULE_ID parameter that would switch a request to include scheduleId and endpointId parameters.

Calling this script using a valid schedule id worked as expected:

```
MS_STAGING=1 SCHEDULE_ID=c0b41a3b-d07b-45c1-b8ed-3e1039b4ceaf node test/manual/test.js
Connecting to https://services-stage.risevision.com/messaging?scheduleId=c0b41a3b-d07b-45c1-b8ed-3e1039b4ceaf&endpointId=1234
messaging service connected https://services-stage.risevision.com
```

and using an invalid schedule id resulted in errors, as expected:
```
MS_STAGING=1 SCHEDULE_ID=c0b41a3b-d07b-45c1-b8ed-3e1039b4ce node test/manual/test.js
Connecting to https://services-stage.risevision.com/messaging?scheduleId=c0b41a3b-d07b-45c1-b8ed-3e1039b4ce&endpointId=1234
messaging error
{ Error: unexpected server response (404)
    at ClientRequest._req.on (/home/santiago/rise/messaging-service/node_modules/ws/lib/WebSocket.js:653:21)
```

Previous scenarios with displayId were also manually tested, and worked as expected.

## Release Plan:
This branch will be merged to parent feature/check_valid_displays branch. Production release as described on parent branch.

- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
-

2021-02-05 18:11 UTC, santiagonoguez commented on src/websocket/primus-setup.js
> +      }
MS uses display id param all over the place to create and manage the data structures ( connections, files, etc ). I considered that the best way to use scheduleId instead of displayId in cases it was provided instead was this one. Otherwise, we would need to revise all the other files to consider this. 

But we could also refactor the code to rename displayId to something else if it becomes confusing ( as not it is displayId or scheduleId ). :O

2021-02-05 20:30 UTC, tejohnso requested changes

2021-02-05 20:30 UTC, tejohnso commented on src/websocket/primus-setup.js
> +      }
I think it's okay to keep using displayId, but it should be populated with the endpointId, not the scheduleId. Since it's the endpointId that is unique per connection.

2021-02-05 20:36 UTC, santiagonoguez commented on src/websocket/primus-setup.js
> +      }
great, thanks, I'll change it !

2021-02-08 14:27 UTC, santiagonoguez commented on src/websocket/primus-setup.js
> +      }
@tejohnso it's now changed to endpointId, thanks !

2021-02-08 14:30 UTC, tejohnso approved these changes

2021-02-08 15:25 UTC, merged